// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	records "github.com/meisbokai/GolangApiTest/internal/datasources/records"
	mock "github.com/stretchr/testify/mock"
)

// Seeder is an autogenerated mock type for the Seeder type
type Seeder struct {
	mock.Mock
}

// UserSeeder provides a mock function with given fields: userData
func (_m *Seeder) UserSeeder(userData []records.Users) error {
	ret := _m.Called(userData)

	if len(ret) == 0 {
		panic("no return value specified for UserSeeder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]records.Users) error); ok {
		r0 = rf(userData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSeeder creates a new instance of Seeder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSeeder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Seeder {
	mock := &Seeder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
