// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	v1 "github.com/meisbokai/GolangApiTest/internal/http/domains/v1"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, inDom
func (_m *UserRepository) CreateUser(ctx context.Context, inDom *v1.UserDomain) error {
	ret := _m.Called(ctx, inDom)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UserDomain) error); ok {
		r0 = rf(ctx, inDom)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: ctx, inDom
func (_m *UserRepository) DeleteUser(ctx context.Context, inDom *v1.UserDomain) error {
	ret := _m.Called(ctx, inDom)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UserDomain) error); ok {
		r0 = rf(ctx, inDom)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllUsers provides a mock function with given fields: ctx
func (_m *UserRepository) GetAllUsers(ctx context.Context) ([]v1.UserDomain, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []v1.UserDomain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]v1.UserDomain, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []v1.UserDomain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.UserDomain)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, inDom
func (_m *UserRepository) GetUserByEmail(ctx context.Context, inDom *v1.UserDomain) (v1.UserDomain, error) {
	ret := _m.Called(ctx, inDom)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 v1.UserDomain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UserDomain) (v1.UserDomain, error)); ok {
		return rf(ctx, inDom)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UserDomain) v1.UserDomain); ok {
		r0 = rf(ctx, inDom)
	} else {
		r0 = ret.Get(0).(v1.UserDomain)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.UserDomain) error); ok {
		r1 = rf(ctx, inDom)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, inDom
func (_m *UserRepository) GetUserByID(ctx context.Context, inDom *v1.UserDomain) (v1.UserDomain, error) {
	ret := _m.Called(ctx, inDom)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 v1.UserDomain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UserDomain) (v1.UserDomain, error)); ok {
		return rf(ctx, inDom)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UserDomain) v1.UserDomain); ok {
		r0 = rf(ctx, inDom)
	} else {
		r0 = ret.Get(0).(v1.UserDomain)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.UserDomain) error); ok {
		r1 = rf(ctx, inDom)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserEmail provides a mock function with given fields: ctx, inDom, newEmail
func (_m *UserRepository) UpdateUserEmail(ctx context.Context, inDom *v1.UserDomain, newEmail string) error {
	ret := _m.Called(ctx, inDom, newEmail)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UserDomain, string) error); ok {
		r0 = rf(ctx, inDom, newEmail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
